### ISSUE TITLE
'EXC_BAD_ACCESS' at CVOpenGLESTextureCacheCreateTextureFromImage in [GPUImageFrameBuffer generateFramebuffer] when use xcode6.4 debugging.

### ISSUE THREAD

**Issue by NianJi** [BradLarson/GPUImage#2046] opened 2015-07-09 05:54 UTC
* thread #60: tid = 0xaa4bf, 0x0000000104b3a90c libglInterpose.dylib`EAGLContext_texImageIOSurface_target_internalFormat_width_height_format_type_plane_invert(EAGLContext*, objc_selector*, __IOSurface*, unsigned long, unsigned long, unsigned int, unsigned int, unsigned long, unsigned long, unsigned int, bool) + 804, queue = 'com.sunsetlakesoftware.GPUImage.openGLESContextQueue', stop reason = EXC_BAD_ACCESS (code=1, address=0x1a598e46d19)
    frame #0: 0x0000000104b3a90c libglInterpose.dylib`EAGLContext_texImageIOSurface_target_internalFormat_width_height_format_type_plane_invert(EAGLContext*, objc_selector*, __IOSurface*, unsigned long, unsigned long, unsigned int, unsigned int, unsigned long, unsigned long, unsigned int, bool) + 804
    frame #1: 0x0000000186d3a240 CoreVideo`CVOpenGLESContext::texImageIOSurface(unsigned int, unsigned int, int, int, unsigned int, unsigned int, __IOSurface*, unsigned int) + 88
    frame #2: 0x0000000186d5233c CoreVideo`CVPixelBufferOpenGLESTextureBacking::createStandardTexture(CVImageBuffer*) + 708
    frame #3: 0x0000000186d52744 CoreVideo`CVPixelBufferOpenGLESTextureBacking::initWithPixelBackingContext(CVPixelBufferBacking*, CVOpenGLESContext*, __CFDictionary const*, CVImageBuffer*, int*) + 252
    frame #4: 0x0000000186d4f100 CoreVideo`CVPixelBufferBacking::createTextureBackingForContext(__CFAllocator const*, CVOpenGLESContext*, __CFDictionary const*, CVImageBuffer*, int*) + 108
    frame #5: 0x0000000186d4c6d4 CoreVideo`CVOpenGLESTextureCache::createTextureBackingFromImageBacking(__CFAllocator const*, CVImageBacking*, CVImageBuffer*, __CFDictionary const*, int*) + 540
    frame #6: 0x0000000186d4c3c4 CoreVideo`CVOpenGLESTextureCache::createTextureFromImageWithParams(__CFAllocator const*, CVImageBuffer*, unsigned int, int, int, int, unsigned int, unsigned int, unsigned long, int*) + 248
    frame #7: 0x0000000186d49e28 CoreVideo`CVOpenGLESTextureCacheCreateTextureFromImage + 184
  * frame #8: 0x00000001006eb9cc Tmall4iPhone`__42-[GPUImageFramebuffer generateFramebuffer]_block_invoke(.block_descriptor=0x0000000113acf680) + 1028 at GPUImageFramebuffer.m:159
    frame #9: 0x000000010070da3c Tmall4iPhone`runSynchronouslyOnVideoProcessingQueue(block=0x0000000113acf680) + 108 at GPUImageOutput.m:27
    frame #10: 0x00000001006eb5a8 Tmall4iPhone`-[GPUImageFramebuffer generateFramebuffer](self=0x0000000174ad0f40, _cmd=0x00000001022b0db3) + 116 at GPUImageFramebuffer.m:133
    frame #11: 0x00000001006eafa8 Tmall4iPhone`-[GPUImageFramebuffer initWithSize:textureOptions:onlyTexture:](self=0x0000000174ad0f40, _cmd=0x00000001022b0fc5, framebufferSize=(width = 1704, height = 958), fboTextureOptions=GPUTextureOptions at 0x0000000113acf898, onlyGenerateTexture=false) + 500 at GPUImageFramebuffer.m:59
    frame #12: 0x00000001006edbc0 Tmall4iPhone`__79-[GPUImageFramebufferCache fetchFramebufferForSize:textureOptions:onlyTexture:]_block_invoke(.block_descriptor=0x0000000113acf998) + 436 at GPUImageFramebufferCache.m:82
    frame #13: 0x000000010070da3c Tmall4iPhone`runSynchronouslyOnVideoProcessingQueue(block=0x0000000113acf998) + 108 at GPUImageOutput.m:27
    frame #14: 0x00000001006ed8d0 Tmall4iPhone`-[GPUImageFramebufferCache fetchFramebufferForSize:textureOptions:onlyTexture:](self=0x00000001724500b0, _cmd=0x00000001022b0fee, framebufferSize=(width = 1704, height = 958), textureOptions=<unavailable>, onlyTexture=false) + 256 at GPUImageFramebufferCache.m:74
    frame #15: 0x00000001006e37a4 Tmall4iPhone`-[GPUImageFilter renderToTextureWithVertices:textureCoordinates:](self=0x000000015cfe7de0, _cmd=0x00000001022afce9, vertices=0x000000010253dd80, textureCoordinates=0x000000010253dc80) + 352 at GPUImageFilter.m:302
    frame #16: 0x00000001006e6618 Tmall4iPhone`-[GPUImageFilter newFrameReadyAtTime:atIndex:](self=0x000000015cfe7de0, _cmd=0x00000001022afccc, frameTime=(value = 0, timescale = 0, flags = 17, epoch = 0), textureIndex=0) + 144 at GPUImageFilter.m:567
    frame #17: 0x0000000100712fdc Tmall4iPhone`__53-[GPUImagePicture processImageWithCompletionHandler:]_block_invoke(.block_descriptor=0x000000015cfe8810) + 680 at GPUImagePicture.m:266
    frame #18: 0x0000000104c18fd4 libdispatch.dylib`_dispatch_call_block_and_release + 24
    frame #19: 0x0000000104c18f94 libdispatch.dylib`_dispatch_client_callout + 16
    frame #20: 0x0000000104c23db8 libdispatch.dylib`_dispatch_queue_drain + 780
    frame #21: 0x0000000104c1c2c4 libdispatch.dylib`_dispatch_queue_invoke + 132
    frame #22: 0x0000000104c265d4 libdispatch.dylib`_dispatch_root_queue_drain + 772
    frame #23: 0x0000000104c28248 libdispatch.dylib`_dispatch_worker_thread3 + 132
    frame #24: 0x000000019828122c libsystem_pthread.dylib`_pthread_wqthread + 816

**Comment by BradLarson** [comment] 2015-07-09 12:48
This appears to be a duplicate of issue #2041

**Closed by BradLarson** 2015-07-09 12:48 UTC
