### ISSUE TITLE
GPUImage Uploaded and makes white holes

### ISSUE THREAD

**Issue by johnny51925** [BradLarson/GPUImage#1952] opened 2015-04-06 05:36 UTC
Hi ,

Do anyone know why the image I uploaded to my server with contain "white holes"?

![_sdki1mbxq2byxh4qnsuo](https://cloud.githubusercontent.com/assets/8379957/7000957/6d5d923e-dc6a-11e4-8c92-726cf683d659.jpg)

**Comment by BradLarson** [comment] 2015-04-06 22:06
This appears to be the same issue as #1823, so I'll close this as a duplicate of that.

**Closed by BradLarson** 2015-04-06 22:06 UTC
