### ISSUE TITLE
SimpleVideoFileFilter not working Perfectly, stop @2%

### ISSUE THREAD

**Issue by mehulparmar4ever** [BradLarson/GPUImage#1927] opened 2015-02-24 11:36 UTC
Attached Screen Shot.

![ios simulator screen shot 24-feb-2015 5 04 57 pm](https://cloud.githubusercontent.com/assets/7687920/6348597/469d1860-bc47-11e4-9bd5-95395f4e60a9.png)

**Comment by BradLarson** [comment] 2015-02-24 15:19
This is a duplicate of issue #1920.

**Closed by BradLarson** 2015-02-24 15:19 UTC

**Comment by mehulparmar4ever** [comment] 2015-02-25 05:48
@BradLarson  , Did you solve this bug?
I have used your Code in my application. Please change it.

**Comment by BradLarson** [comment] 2015-02-25 16:34
"Please change it."

You do realize this is a hobby project that I do in my spare time, right? That you get for free? If this is that urgent for you to solve, you have all the source code you need. 

Fix it yourself, and I'll gladly accept a pull request that resolves this.

**Comment by mehulparmar4ever** [comment] 2015-05-01 07:53
ok. Brad, i will try to solve that. if i got solution, will inform you.
btw tnks.

Mehul Parmar

*iPhone App Developer*

Cell: 91-9998585499

mehulasjack@gmail.com
