### ISSUE TITLE
CVOpenGLESTextureCacheCreateTextureFromImage Error

### ISSUE THREAD

**Issue by noranecoco** [BradLarson/GPUImage#2053] opened 2015-07-17 10:40 UTC
Hi, I met a problem when camera application try to do image processing with GPUImage in simulator.
But there are no problems in particular when camera application try to do image processing with GPUImage in iPhone6.
 It shows,
Camera CVOpenGLESTextureCacheCreateTextureFromImage failed (error: -6661)

<img width="852" alt="2015-07-17 19 32 23" src="https://cloud.githubusercontent.com/assets/13379597/8745437/dee8261c-2cba-11e5-94fb-03dfc6dd440c.png">

Can you help fixing that?

**Comment by noranecoco** [comment] 2015-07-17 10:48
Same error shows when doing debug by using iPhone5.

**Comment by BradLarson** [comment] 2015-07-17 14:14
This appears to be a duplicate of issue #2041.

**Closed by BradLarson** 2015-07-17 14:14 UTC

**Comment by noranecoco** [comment] 2015-07-17 16:32
I am glad to inform you that the problem is now solved.
Thank you very much!

**Comment by caixindong** [comment] 2026-03-18 06:47
The texture upload failed; try uploading the texture manually.

**Comment by ygsky** [comment] 2026-03-18 06:49
来信已收到，我会尽快查看！
